"""P6: Rule-based Diagnosis Engine — traceable, evidence-backed diagnostics.

All diagnosis conclusions are generated by matching probe data against
configurable rules. Each conclusion MUST cite specific evidence from
llm_probe_results. No hardcoded template conclusions.

Rules are stored in database and can be customized per industry/tenant.
"""

import uuid
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

# ── Default diagnosis rules (seeded on first use) ────────────
DEFAULT_RULES = [
    # ── Brand exposure rules ─────────────────────────────────
    {
        "rule_name": "brand_completely_invisible",
        "rule_category": "exposure",
        "condition_json": {"field": "mention_rate", "operator": "eq", "value": 0},
        "problem": "大模型生态完全空白",
        "reason": "该模型生态内无有效采信信源，大模型无品牌内容可引用，导致品牌在该平台完全不可见",
        "suggestion": "优先创建该模型生态内的内容资产，补充实景素材和品牌基础信息",
        "level": "high",
        "evidence_field": "llm_probe_results.model_id",
        "target_models": None,  # Applies to all models
        "sort_order": 1,
    },
    {
        "rule_name": "brand_low_exposure",
        "rule_category": "exposure",
        "condition_json": {"field": "mention_rate", "operator": "lt", "value": 30},
        "problem": "品牌曝光严重不足",
        "reason": "该模型生态内品牌内容量远低于行业基准，竞品更容易被推荐",
        "suggestion": "加快内容产出频率，每周至少2篇深度原创，覆盖行业关键词",
        "level": "high",
        "evidence_field": "llm_probe_results.model_id",
        "target_models": None,
        "sort_order": 2,
    },
    # ── Content gap rules ────────────────────────────────────
    {
        "rule_name": "no_real_photo_assets",
        "rule_category": "multimodal",
        "condition_json": {"field": "multimodal_assets_count", "operator": "lt", "value": 3},
        "problem": "实景实拍素材严重缺失",
        "reason": "缺少工厂/产品实拍图，大模型判定企业线下实力弱、真实度低，大幅降低推荐意愿",
        "suggestion": "拍摄工厂全景+产线实拍+产品细节图至少10张，上传至知识库多模态资产",
        "level": "high",
        "evidence_field": "kb_assets.asset_type",
        "target_models": ["doubao", "yuanbao"],
        "sort_order": 3,
    },
    {
        "rule_name": "no_baidu_encyclopedia",
        "rule_category": "basic_asset",
        "condition_json": {"field": "has_encyclopedia", "operator": "eq", "value": False},
        "problem": "百度百科词条缺失",
        "reason": "文心一言等百度生态模型将百度百科作为核心权威信源，无词条直接导致品牌权威度为零",
        "suggestion": "创建/优化百度百科词条，确保企业名称、资质、产品信息完整准确",
        "level": "high",
        "evidence_field": "identity_baseline.encyclopedia_entry_exists",
        "target_models": ["wenxin"],
        "sort_order": 4,
    },
    # ── Competitor gap rules ─────────────────────────────────
    {
        "rule_name": "competitor_exposure_gap_large",
        "rule_category": "competitor",
        "condition_json": {"field": "exposure_gap_ratio", "operator": "gt", "value": 3},
        "problem": "竞品曝光差距悬殊",
        "reason": "竞品在各模型中的品牌曝光量是您的3倍以上，大量潜在客户被竞品截流",
        "suggestion": "立即启动竞品对标分析，针对性补强竞品领先的内容维度和渠道",
        "level": "high",
        "evidence_field": "competitor_benchmark.exposure_gap",
        "target_models": None,
        "sort_order": 5,
    },
    # ── Sentiment rules ──────────────────────────────────────
    {
        "rule_name": "negative_sentiment_detected",
        "rule_category": "sentiment",
        "condition_json": {"field": "negative_count", "operator": "gt", "value": 0},
        "problem": "检测到负面舆情",
        "reason": "有模型在回答中提及了品牌的负面信息或投诉内容，直接影响潜在客户决策",
        "suggestion": "立即创建澄清内容，在对应平台发布正面信息对冲负面影响",
        "level": "high",
        "evidence_field": "llm_probe_results.has_negative",
        "target_models": None,
        "sort_order": 6,
    },
    {
        "rule_name": "info_conflict_detected",
        "rule_category": "accuracy",
        "condition_json": {"field": "has_error_info", "operator": "eq", "value": True},
        "problem": "模型回答中存在企业信息错误",
        "reason": "模型引用了过时或错误的品牌信息，导致用户获取不准确的企业认知",
        "suggestion": "在各权威信源统一更新企业信息，确保多平台信息一致性",
        "level": "medium",
        "evidence_field": "llm_probe_results.has_error_info",
        "target_models": None,
        "sort_order": 7,
    },
]


class DiagnosisRuleEngine:
    """Rule-based diagnostic engine with evidence binding.

    Matches probe data against configurable rules to generate
    precise, traceable diagnosis conclusions.
    """

    def __init__(self, db: AsyncSession, tenant_id: uuid.UUID):
        self.db = db
        self.tenant_id = tenant_id

    async def ensure_default_rules(self):
        """Seed default rules if none exist for this tenant."""
        from app.services.layered_diagnosis.models import DiagnosisRule

        existing = await self.db.execute(
            select(DiagnosisRule).where(
                (DiagnosisRule.customer_id == self.tenant_id) |
                (DiagnosisRule.customer_id.is_(None)),
                DiagnosisRule.is_active == True,
            )
        )
        if existing.scalars().first():
            return

        for rule_data in DEFAULT_RULES:
            self.db.add(DiagnosisRule(
                customer_id=None,  # Global rule
                **rule_data,
            ))
        await self.db.flush()

    async def evaluate(self, probe_summary: dict, identity_data: dict,
                        competitor_data: dict, kb_status: dict) -> list[dict]:
        """Evaluate all active rules against current data.

        Returns list of triggered diagnoses with evidence bindings.
        """
        from app.services.layered_diagnosis.models import DiagnosisRule

        rules = (await self.db.execute(
            select(DiagnosisRule).where(
                (DiagnosisRule.customer_id == self.tenant_id) |
                (DiagnosisRule.customer_id.is_(None)),
                DiagnosisRule.is_active == True,
            ).order_by(DiagnosisRule.sort_order)
        )).scalars().all()

        diagnoses = []
        for rule in rules:
            if self._match_condition(rule, probe_summary, identity_data,
                                      competitor_data, kb_status):
                diagnoses.append({
                    "rule_id": str(rule.id),
                    "rule_name": rule.rule_name,
                    "category": rule.rule_category,
                    "problem": rule.problem,
                    "reason": rule.reason,
                    "suggestion": rule.suggestion,
                    "level": rule.level,
                    "evidence_field": rule.evidence_field,
                    "evidence_source": self._extract_evidence(rule, probe_summary, identity_data),
                    "target_models": rule.target_models,
                })
        return diagnoses

    def _match_condition(self, rule, probe: dict, identity: dict,
                          competitor: dict, kb: dict) -> bool:
        """Evaluate a single rule condition against data."""
        cond = rule.condition_json
        if not isinstance(cond, dict):
            return False
        field = cond.get("field", "")
        operator = cond.get("operator", "eq")
        value = cond.get("value")

        # Resolve the actual value from probe data
        actual = self._resolve_field(field, probe, identity, competitor, kb)
        if actual is None:
            return False

        # Apply operator
        if operator == "eq":
            return actual == value
        elif operator == "lt":
            return isinstance(actual, (int, float)) and actual < value
        elif operator == "gt":
            return isinstance(actual, (int, float)) and actual > value
        elif operator == "gte":
            return isinstance(actual, (int, float)) and actual >= value
        elif operator == "lte":
            return isinstance(actual, (int, float)) and actual <= value
        return False

    def _resolve_field(self, field: str, probe: dict, identity: dict,
                        competitor: dict, kb: dict):
        """Resolve a dotted field path to actual value."""
        if field == "mention_rate":
            return self._extract_mention_rate(probe)
        elif field == "multimodal_assets_count":
            return kb.get("multimodal", {}).get("has", 0)
        elif field == "has_encyclopedia":
            return identity.get("encyclopedia_entry_exists", False)
        elif field == "exposure_gap_ratio":
            return competitor.get("exposure_gap_ratio", 0)
        elif field == "negative_count":
            return probe.get("negative_count", 0)
        elif field == "has_error_info":
            return probe.get("has_error_info", False)
        return None

    def _extract_mention_rate(self, probe: dict) -> float:
        """Extract overall brand mention rate from probe summary."""
        models = probe.get("model_summary", {})
        if not models:
            return 0
        rates = [m.get("mention_rate", 0) for m in models.values()]
        return sum(rates) / len(rates) if rates else 0

    def _extract_evidence(self, rule, probe: dict, identity: dict) -> dict:
        """Extract specific evidence values for traceability."""
        field = rule.evidence_field
        return {
            "field": field,
            "value": self._resolve_field(field, probe, identity, {}, {}),
            "rule_name": rule.rule_name,
        }
